mark_as_done:
  name: Mark as done
  description: >
    Sets the last done date of the task to today.
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the task to be marked as done.
      required: true
      selector:
        entity:
          domain: sensor
set_last_done_date:
  name: Set last done date
  description: >
    Sets the last done date of the task to a specific date.
  fields:
    entity_id:
      name: Entity ID
      description: The ID of the task to be updated.
      required: true
      selector:
        entity:
          domain: sensor
    date:
      name: Date
      description: The new last done Date
      required: true
      selector:
        date: